cmake_minimum_required(VERSION 3.20)
if(ARGUMENT_CONTROL)
    if(NOT CMAKE_ARGC EQUAL 12 OR NOT CMAKE_ARGV4 STREQUAL "--")
        message(FATAL_ERROR "argument control expected 12 arguments with '--', got ${CMAKE_ARGC}")
    endif()
    set(expected5 "")
    set(expected6 left)
    set(expected7 "")
    set(expected8 "right ; with space")
    set(expected9 [=[brackets "quotes" \path ${UNDEFINED}]=])
    set(expected10 "\nline\n")
    set(expected11 "")
    foreach(i RANGE 5 11)
        if(NOT "${CMAKE_ARGV${i}}" STREQUAL "${expected${i}}")
            message(FATAL_ERROR "argument control changed argument ${i}")
        endif()
    endforeach()
    message(STATUS "exact argument vector preserved")
    return()
endif()
if(DEFINED DIAGNOSTIC)
    if(DIAGNOSTIC STREQUAL "cmake")
        message(WARNING "deliberate consumer oracle warning")
    elseif(DIAGNOSTIC STREQUAL "deprecation")
        message(DEPRECATION "deliberate consumer oracle deprecation")
    elseif(DIAGNOSTIC STREQUAL "linker")
        message("ld: warning: deliberate consumer oracle warning")
    elseif(DIAGNOSTIC STREQUAL "driver")
        message("clang: warning: deliberate consumer oracle warning")
    elseif(DIAGNOSTIC STREQUAL "promoted")
        message("probe.c:1: error: deliberate diagnostic [-Werror=unused-variable]")
    elseif(DIAGNOSTIC STREQUAL "clean")
        message("consumer clean control")
    else()
        message(FATAL_ERROR "unknown diagnostic fixture")
    endif()
    return()
endif()

if(NOT ORACLE_ROOT OR NOT CTEST_COMMAND)
    message(FATAL_ERROR "missing oracle root or CTest executable")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/RejectConsumerWarnings.cmake")
moq_consumer_warning_patterns(patterns)
set(WORK "${ORACLE_ROOT}/arguments")
moq_consumer_execute(COMMAND "${CMAKE_COMMAND}" -DARGUMENT_CONTROL=ON
    -P "${CMAKE_CURRENT_LIST_FILE}" --
    "" left "" "right ; with space" [=[brackets "quotes" \path ${UNDEFINED}]=]
    "\nline\n" "" RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT rc STREQUAL "0" OR NOT out MATCHES "exact argument vector preserved")
    message(FATAL_ERROR "consumer argument preservation failed: ${out}${err}")
endif()
foreach(kind clean cmake deprecation linker driver promoted)
    set(dir "${ORACLE_ROOT}/${kind}")
    file(MAKE_DIRECTORY "${dir}")
    file(WRITE "${dir}/CTestTestfile.cmake"
        "add_test(diagnostic \"${CMAKE_COMMAND}\" -DCMAKE_WARN_DEPRECATED=ON -DDIAGNOSTIC=${kind} -P \"${CMAKE_CURRENT_LIST_FILE}\")\n"
        "set_tests_properties(diagnostic PROPERTIES FAIL_REGULAR_EXPRESSION [==[${patterns}]==])\n")
    execute_process(COMMAND "${CTEST_COMMAND}" --test-dir "${dir}" -V
        RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    file(WRITE "${dir}/receipt.log" "${out}${err}")
    if(out MATCHES "RegularExpression::compile" OR err MATCHES "RegularExpression::compile")
        message(FATAL_ERROR "consumer diagnostic regex could not compile: ${out}${err}")
    endif()
    if(kind STREQUAL "clean")
        if(NOT rc STREQUAL "0" OR NOT out MATCHES "100% tests passed")
            message(FATAL_ERROR "clean consumer diagnostic control failed: ${out}${err}")
        endif()
    elseif(NOT rc STREQUAL "8" OR NOT out MATCHES "Error regular expression found in output")
        message(FATAL_ERROR "consumer diagnostic ${kind} escaped or failed for another reason: ${out}${err}")
    endif()
    message(STATUS "consumer diagnostic ${kind}: expected verdict")
endforeach()
