include_guard(GLOBAL)

# Cache preload rather than command-line hints: C-only children may legitimately
# ignore C++ settings without producing unused-variable diagnostics.
function(moq_write_consumer_context path)
    set(vars CMAKE_TOOLCHAIN_FILE CMAKE_BUILD_TYPE CMAKE_TRY_COMPILE_CONFIGURATION
        CMAKE_SYSROOT CMAKE_SYSROOT_COMPILE CMAKE_SYSROOT_LINK
        CMAKE_OSX_SYSROOT CMAKE_OSX_ARCHITECTURES CMAKE_OSX_DEPLOYMENT_TARGET)
    if(CMAKE_CROSSCOMPILING)
        list(APPEND vars CMAKE_SYSTEM_NAME CMAKE_SYSTEM_PROCESSOR)
    endif()
    foreach(lang C CXX)
        list(APPEND vars CMAKE_${lang}_COMPILER CMAKE_${lang}_COMPILER_ARG1
            CMAKE_${lang}_COMPILER_TARGET CMAKE_${lang}_COMPILER_EXTERNAL_TOOLCHAIN
            CMAKE_${lang}_FLAGS)
        foreach(config DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
            list(APPEND vars CMAKE_${lang}_FLAGS_${config})
        endforeach()
    endforeach()
    list(APPEND vars CMAKE_EXE_LINKER_FLAGS)
    foreach(config DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
        list(APPEND vars CMAKE_EXE_LINKER_FLAGS_${config})
    endforeach()
    set(content "# Selected producer build context; dependencies remain explicit.\n")
    foreach(var IN LISTS vars)
        if(DEFINED ${var})
            set(eq "=")
            string(FIND "${${var}}" "]${eq}]" found)
            while(NOT found EQUAL -1)
                string(APPEND eq "=")
                string(FIND "${${var}}" "]${eq}]" found)
            endwhile()
            string(APPEND content "set(${var} [${eq}[${${var}}]${eq}] CACHE STRING \"Producer build context\" FORCE)\n")
        endif()
    endforeach()
    file(WRITE "${path}" "${content}")
    set(json "{}")
    foreach(lang C CXX LINK)
        moq_consumer_direct_flags(${lang} flags)
        set(array "[]")
        set(i 0)
        foreach(flag IN LISTS flags)
            string(REPLACE "\\" "\\\\" quoted "${flag}")
            string(REPLACE "\"" "\\\"" quoted "${quoted}")
            string(REPLACE "\n" "\\n" quoted "${quoted}")
            string(REPLACE "\r" "\\r" quoted "${quoted}")
            string(REPLACE "\t" "\\t" quoted "${quoted}")
            string(JSON array SET "${array}" ${i} "\"${quoted}\"")
            math(EXPR i "${i} + 1")
        endforeach()
        string(JSON json SET "${json}" "${lang}" "${array}")
    endforeach()
    file(WRITE "${path}.json" "${json}\n")
endfunction()

# Flags for test-owned pkg-config invocations, not package metadata.
function(moq_consumer_direct_flags lang out)
    string(TOUPPER "${CMAKE_BUILD_TYPE}" config)
    if(lang STREQUAL "LINK")
        set(raw "${CMAKE_EXE_LINKER_FLAGS} ${CMAKE_EXE_LINKER_FLAGS_${config}}")
    else()
        set(raw "${CMAKE_${lang}_COMPILER_ARG1} ${CMAKE_${lang}_FLAGS} ${CMAKE_${lang}_FLAGS_${config}}")
    endif()
    separate_arguments(flags NATIVE_COMMAND "${raw}")
    if(NOT lang STREQUAL "LINK")
        if(CMAKE_${lang}_COMPILER_TARGET)
            list(APPEND flags "--target=${CMAKE_${lang}_COMPILER_TARGET}")
        endif()
        if(CMAKE_${lang}_COMPILER_EXTERNAL_TOOLCHAIN)
            list(APPEND flags "--gcc-toolchain=${CMAKE_${lang}_COMPILER_EXTERNAL_TOOLCHAIN}")
        endif()
        if(CMAKE_OSX_SYSROOT)
            list(APPEND flags -isysroot "${CMAKE_OSX_SYSROOT}")
        elseif(CMAKE_SYSROOT)
            list(APPEND flags "--sysroot=${CMAKE_SYSROOT}")
        endif()
        foreach(arch IN LISTS CMAKE_OSX_ARCHITECTURES)
            list(APPEND flags -arch "${arch}")
        endforeach()
        if(CMAKE_OSX_DEPLOYMENT_TARGET AND CMAKE_SYSTEM_NAME STREQUAL "Darwin")
            list(APPEND flags "-mmacosx-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}")
        endif()
    endif()
    set(${out} "${flags}" PARENT_SCOPE)
endfunction()
