foreach(_v SRC WORK BUILD CONSUMER_CONTEXT)
    if(NOT DEFINED ${_v} OR "${${_v}}" STREQUAL "")
        message(FATAL_ERROR "pass -D${_v}=<path>")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/../../../tests/cmake/RejectConsumerWarnings.cmake")
file(REMOVE_RECURSE "${WORK}")

set(_hints)
foreach(_pair "PICOQUIC_SOURCE_DIR;MOQ_PICOQUIC_SOURCE_DIR" "PICOTLS_PREFIX;MOQ_PICOTLS_PREFIX")
    list(GET _pair 0 _input)
    list(GET _pair 1 _cache)
    if(DEFINED ${_input} AND NOT "${${_input}}" STREQUAL "")
        string(REPLACE ";" "\\;" _value "${${_input}}")
        list(APPEND _hints "-D${_cache}=${_value}")
    endif()
endforeach()
moq_consumer_execute(COMMAND "${CMAKE_COMMAND}" -C "${CONSUMER_CONTEXT}"
    -S "${SRC}" -B "${WORK}" "-DCMAKE_PREFIX_PATH=${BUILD}" ${_hints}
    RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _out)
if(NOT _rc STREQUAL "0")
    message(FATAL_ERROR "C++ consumer configure failed: ${_rc}\n${_out}")
endif()
moq_consumer_execute(COMMAND "${CMAKE_COMMAND}" --build "${WORK}"
    RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _out)
if(NOT _rc STREQUAL "0")
    message(FATAL_ERROR "C++ consumer build failed: ${_rc}\n${_out}")
endif()
moq_consumer_execute(COMMAND "${WORK}/moq_consumer_test"
    RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _out)
if(NOT _rc STREQUAL "0")
    message(FATAL_ERROR "C++ consumer run failed: ${_rc}\n${_out}")
endif()
message(STATUS "cpp_consumer: OK")
